# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_convolutions.ipynb.

# %% auto 0
__all__ = ['def_device', 'conv', 'to_device', 'collate_device']

# %% ../nbs/07_convolutions.ipynb 2
import torch
from torch import nn

from torch.utils.data import default_collate
from typing import Mapping

from .training import *
from .datasets import *

# %% ../nbs/07_convolutions.ipynb 78
def conv(ni, nf, ks=3, stride=2, act=True):
    # conv layer with padding to keep the image size fixed (without accounting for stride)
    res = nn.Conv2d(ni, nf, stride=stride, kernel_size=ks, padding=ks//2)
    # optionally add activation layer
    if act: res = nn.Sequential(res, nn.ReLU())
    return res

# %% ../nbs/07_convolutions.ipynb 84
def_device = 'mps' if torch.backends.mps.is_available() else 'cuda' if torch.cuda.is_available() else 'cpu'

def to_device(x, device=def_device):
    # if tensor -> move it to device
    if isinstance(x, torch.Tensor): return x.to(device)
    # if Mapping -> move each value to a device
    if isinstance(x, Mapping): return {k:v.to(device) for k,v in x.items()}
    # if not tensor or Mapping -> move it (and each of its element) to a device
    return type(x)(to_device(o, device) for o in x)

def collate_device(b): return to_device(default_collate(b))
