# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_accel_sgd.ipynb.

# %% auto 0
__all__ = ['BaseSchedCB', 'BatchSchedCB', 'HasLearnCB', 'RecorderCB', 'EpochSchedStep']

# %% ../nbs/12_accel_sgd.ipynb 2
import torch

from .datasets import *
from .conv import *
from .learner import *
from .activations import *
from .init import *
from typing import Callable

# %% ../nbs/12_accel_sgd.ipynb 58
class BaseSchedCB(Callback):
    def __init__(self, sched: Callable): self.sched = sched
    def before_fit(self, learn): self.schedo = self.sched(learn.opt)
    def _step(self, learn):
        # step with a scheduler
        if learn.training: self.schedo.step()

# %% ../nbs/12_accel_sgd.ipynb 59
class BatchSchedCB(BaseSchedCB):
    def after_batch(self, learn): self._step(learn)

# %% ../nbs/12_accel_sgd.ipynb 60
class HasLearnCB(Callback):
    def before_fit(self, learn): self.learn = learn
    def after_fit(self, learn): self.learn = None

# %% ../nbs/12_accel_sgd.ipynb 62
class RecorderCB(Callback):
    def __init__(self, **d): self.d = d
    
    def before_fit(self, learn):
        # create a dict of names (of stuff to track) and function (to grab that stuff)
        # the function will take a cb as input and index into cb.pg to grab what it needs
        self.recs = {k:[] for k in self.d}
        # grab the first parameter group to track
        self.pg = learn.opt.param_groups[0]
    
    def after_batch(self, learn):
        if not learn.training: return
        for k,v in self.d.items():
            self.recs[k].append(v(self))
    
    def plot(self):
        for k,v in self.recs.items():
            plt.plot(v, label=k)
            plt.legend()
            plt.show()

# %% ../nbs/12_accel_sgd.ipynb 70
class EpochSchedStep(BaseSchedCB):
    def after_epoch(self, learn): self._step(learn)
